---
title: "Integrate ST Data"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    code-fold: show
params:
  fig.path: "`r paste0(params$fig.path)`" #./Figures/
editor_options: 
  chunk_output_type: console
---

```{r background_job, eval=FALSE, include=FALSE}
source("../bin/render_with_jobs.R")
file_name <- "./02_integrate_st_data.md"
lab_dir <- "../lab_book/02_QC_integrate_st_data/"

file <- paste0(basename(xfun::sans_ext(file_name)), '_', Sys.Date(), '.html')

# quarto
# render_html_with_job(out_dir = lab_dir)
# fs::file_move(path = file, new_path = paste0(lab_dir, file))

# currently using quarto for github and kniter for html du to source code option 
render_git_with_job(fig_path = "../Figures/02/")

# kniter
knit_html_with_job(out_dir = lab_dir, fig_path = "./Figures/02/")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(#fig.width = 6.6929133858,
    fig.path    = params$fig.path,
    dev         = c("png"),
    dpi         = 300,
    fig.align   = "center",
    message     = FALSE,
    warning     = FALSE,
    fig.process = function(filename){
      new_filename <- stringr::str_remove(string = filename, 
                                        pattern = "-1")
      fs::file_move(path = filename, new_path = new_filename)
      ifelse(fs::file_exists(new_filename), new_filename, filename)})
# setwd("/Users/vilkal/work/Brolidens_work/Projects/Spatial_DMPA/src")
```

## Load data and libraries

```{r Load_Library_and_data}
##################
# LOAD LIBRARIES #
##################
library(tidyverse)
library(Seurat)
library(tidyseurat)
library(cowplot)
library(harmony)

#########
# PATHS #
#########
input_dir <- "../results/01_QC_st_data/"
#input_dir <- "../results/00_load_st_data/"
result_dir <- "../results/02_integrate_st_data/"
if( isFALSE(dir.exists(result_dir)) ) { dir.create(result_dir,recursive = TRUE) }

#############
# LODA DATA #
#############
#DATA <- readRDS(paste0(input_dir,"seuratObj_filtered.RDS"))
DATA <- readRDS(paste0(input_dir,"seuratObj_merged.RDS"))

```

```{r ggplot_theme}
my_theme <-
  list(
    #scale_fill_manual(values = friendly_cols),
    #scale_color_manual(values = friendly_cols),
    theme_bw() +
      #guides(color = guide_legend(override.aes = list(size=2, alpha = 1))) +
      theme(
        panel.border = element_blank(),
        axis.line = element_line(),
        panel.grid.major = element_line(size = 0.2),
        panel.grid.minor = element_line(size = 0.1),
        text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        #legend.position = "bottom",
        #aspect.ratio = 1,
        strip.background = element_blank(),
        axis.title.x = element_text(margin = margin(t = 10, r = 10, b = 10, l = 10)),
        axis.title.y = element_text(margin = margin(t = 10, r = 10, b = 10, l = 10))
      )
  )
```

## Identify Highly Variable Genes (HVG) across samples

```{r Find_HVG}
################################
# SPLIT INTO SEPERATE DATASETS #
################################
DATA_nested <- DATA %>%
  mutate(batch = orig.ident) %>%
  nest(data = -batch) %>%
  mutate(data = imap(
    data, ~ .x %>%
      NormalizeData(., normalization.method = "LogNormalize", 
                    verbose = FALSE) %>%
      FindVariableFeatures(selection.method = "vst", 
                           nfeatures = 2000, 
                           verbose = FALSE) )) %>%
  mutate(data = setNames(.[["data"]], .$batch))

#########################################
# FIND HIGLY VARIABLE GENES PER DATASET #
#########################################
hvgs_heat <- DATA_nested %>%
  .$data %>%
  map(., ~ .x@assays$RNA@var.features) %>%
  ( function(x){unique(unlist(x)) ->> hvgs_all; return(x)} ) %>%
  # intersect across all samples:
  ( function(x){Reduce(intersect, x) ->> hvgs; return(x)} ) %>% 
  imap_dfc(., ~hvgs_all %in% .x, .id=.y) %>%
  mutate(rownames = hvgs_all) %>%
  column_to_rownames(var = "rownames")

# choose the hvg present in at least two samples:
hig_var <- rownames(hvgs_heat)[rowSums(hvgs_heat)>2]

# remove all VDJ-genes from list of HVG
remove <- str_subset(hig_var, "^IGH|^IGK|^IGL|^TRA|^TRB|^TRD|^TRG")
hig_var <- setdiff(hig_var, remove)
```

## Heatmap of HVG in all samples

```{r 02a_HVG_heatmap, fig.width=10}
pheatmap::pheatmap(t(hvgs_heat * 1), cluster_rows = F, color = c("grey90", "grey20"))
```

## Integration

```{r Integration}
############
# HARMONY #
###########
DATA <- DATA %>%
  #filter(sample_name == "CX3" | sample_name == "CX1") %>%
  NormalizeData(verbose = FALSE) %>%
  FindVariableFeatures(selection.method = "vst",
                      nfeatures = 4000,
                      verbose = FALSE) %>%
  ScaleData(verbose = FALSE, features = hig_var ) %>%
  RunPCA(verbose = FALSE, npcs = 50) %>%
  RunUMAP(dims = 1:20, n.components = 2L, n.neighbors = 10) 

DATA <- DATA %>%
  RunHarmony(group.by.vars = "orig.ident", 
             reduction = "pca", 
             dims.use = 1:20, 
             assay.use = "RNA") #%>%
 DATA <-   DATA %>%
  RunUMAP(dims = 1:10, 
          n.neighbors = 10,
          reduction = "harmony",
          reduction.name = "umap_harmony")



```

## Plot before and after integration

```{r 02b_Plot_dim_reduction, fig.width=10, fig.height=6}
plot_clusters.fun <- function(obj, cluster="sample_name", red = "umap_harmony", color = "Brew_all", lable = TRUE, title = NULL){
  if(color == "Brew_all"){
    pal <- c(scales::hue_pal()(8),
             RColorBrewer::brewer.pal(9,"Set1"),
             RColorBrewer::brewer.pal(8,"Set2"),
             RColorBrewer::brewer.pal(8,"Accent"),
             RColorBrewer::brewer.pal(9,"Pastel1"),
             RColorBrewer::brewer.pal(8,"Pastel2") )}
  
  cluster <- sym(cluster)
  feat <- obj %>%
    select(.cell, !!(cluster), orig.ident, nCount_RNA, nFeature_RNA) %>%
    group_by(!!(cluster)) %>%
    add_tally() %>%
    arrange(nFeature_RNA) %>%
    arrange(desc(n))
    
  lable_df <- feat %>%
    select(!!(cluster), contains(red)) %>% 
    summarize_all(mean)
  
  if(lable == TRUE){
    text <- geom_text(data = lable_df, aes(label = !!cluster), col="black") +
      NoLegend() + labs(color= "Clusters")}
  else{text <- labs(color= "")}
  
  red_1 <- sym(paste0(red, "_1"))
  red_2 <- sym(paste0(red, "_2"))
  
  p <- ggplot(feat, aes(!!(red_1), !!(red_2), 
                        color = !!cluster), label = lable) + 
    geom_point(alpha = 0.5, size=.5) + ggtitle(title) + text +
    #ggrepel::geom_label_repel(data = lable, aes(label = !!cluster)) +
    scale_colour_manual(values = pal)  +
    my_theme 
  return(p)
}

res <- c("PC", "harmony", "UMAP", "umap_harmony")
title <- c("PCA raw data", "PCA Harmony integrated", "UMAP raw data", "UMAP Harmony integrated")
p <- map2(res, title, ~plot_clusters.fun(DATA, cluster="orig.ident", red=.x, lable=FALSE, title=.y))
plot_grid(ncol = 2, 
         plotlist = p)
```

## Plot marker genes

```{r 02c_plot_marker_genes, fig.width=10}
################################
# VISUALIZE EXPR. OF KEY GENES #
################################
#library(viridis)
col=c("grey90","grey80","grey60","navy","black")
genes <- c("KRT1", "KRT15", "CDH1")
# genes <- c("CD8A", "SFRP2", "CD3E")
# genes <- c("CD8A", "MYOZ2", "CD3E", "EPCAM", "COL6A1", "CD4")
DATA <- DATA %>%
  mutate(., FetchData(., vars = genes) )

# obj <- DATA       
# gene <- sym("SFRP2")
plot_genes.fun <- function(obj, gene, mins=NULL, maxs=NULL, red = "umap_harmony"){
  gene <- sym(gene)
  feat <- pull(obj, gene)
  
  # Colour pal:
  if(is.null(mins)){mins <- min(c(feat,0),na.rm = T)}
  if(is.null(maxs)){
    maxs <- quantile(feat,0.99,na.rm = T)
    if(maxs==0){maxs <- max(feat,na.rm = T)}
  }
  if(max(feat,na.rm = T) != 0){
    feat <- (feat - mins) / ( maxs - mins)
    feat[feat > 1] <- 1}
  
  red_1 <- sym(paste0(red, "_1"))
  red_2 <- sym(paste0(red, "_2"))
  
  myPalette <-  colorRampPalette(col[-1])
  obj <- arrange(obj,nCount_RNA)
  
  p <- ggplot(obj, aes(!!(red_1), !!(red_2), color = !!(gene)) ) + 
    
    geom_point(alpha = 0.5, size=.5) + ggtitle(as_label(gene)) +
    #scale_color_viridis(option = "D", na.value="#EBECF0") +
    scale_colour_gradientn(colours = c( col[1], myPalette(99)), limits=c(mins, maxs))  +
    my_theme + theme_void() + 
    theme(legend.position = "bottom",
          plot.title = element_text(hjust = 0.5)) #+ NoLegend()
  return(p)
}

# get approximate max value for among all features (genes)
red <- DATA@reductions[["umap_harmony"]]@cell.embeddings
max <- quantile(red,0.99,na.rm = T)

#p <- map(genes, ~plot_genes.fun(DATA, .x, maxs = max))
p <- map(genes, ~plot_genes.fun(DATA, .x))
plot_grid(ncol = 3, 
          plotlist = p)

```

# Paulos base R code

```{r Paulos_HVG, eval=FALSE, include=FALSE}
DATA.list <- SplitObject(DATA, split.by = "sample_name")

for (i in 1:length(DATA.list)) {
    DATA.list[[i]] <- NormalizeData(DATA.list[[i]], verbose = FALSE)
    DATA.list[[i]] <- FindVariableFeatures(DATA.list[[i]], selection.method = "vst",
        nfeatures = 2000, verbose = FALSE)
}

hvgs_per_dataset <- lapply(DATA.list, function(x) {
    x@assays$RNA@var.features
})
# venn::venn(hvgs_per_dataset,opacity = .4,zcolor = scales::hue_pal()(3),cexsn
# = 1,cexil = 1,lwd=1,col='white',frame=F,borders = NA)

temp <- unique(unlist(hvgs_per_dataset))
overlap <- sapply(hvgs_per_dataset, function(x) {
    temp %in% x
})
rownames(overlap) <- temp
pheatmap::pheatmap(t(overlap * 1), cluster_rows = F, color = c("grey90", "grey20"))
```

```{r Paulos_harmony, eval=FALSE, include=FALSE}
hig_var <- rownames(overlap)[rowSums(overlap)>2]
DATA <- DATA %>%
  NormalizeData(verbose = FALSE) %>%
  FindVariableFeatures(selection.method = "vst",
                      nfeatures = 4000,
                      verbose = FALSE) %>%
  ScaleData(verbose = FALSE, features = hig_var ) %>%
  RunPCA(verbose = FALSE, npcs = 50) %>%
  RunUMAP(dims = 1:50, n.components = 2L) 

DATA <- RunHarmony(DATA, group.by.vars = "sample_name", reduction = "pca",
    dims.use = 1:50, assay.use = "RNA")

DATA <- RunUMAP(DATA, dims = 1:30, reduction = "harmony", reduction.name = "umap_harmony")
```

```{r Plot_dimreduction, eval=FALSE, fig.width=10, include=FALSE}
plot_grid(ncol = 2,
  DimPlot(DATA, reduction = "pca", group.by = "orig.ident")+NoAxes()+ggtitle("PCA raw_data"),
  DimPlot(DATA, reduction = "umap", group.by = "orig.ident")+NoAxes()+ggtitle("UMAP raw_data"),
  
  DimPlot(DATA, reduction = "harmony", group.by = "orig.ident")+NoAxes()+ggtitle("harmony integrated"),
  DimPlot(DATA, reduction = "umap_harmony", group.by = "orig.ident")+NoAxes()+ggtitle("UMAP harmony integrated")
  
  # DimPlot(DATA_int_log, reduction = "pca", group.by = "sample_name")+NoAxes()+ggtitle("PCA integrated"),
  # DimPlot(DATA_int_log, reduction = "tsne", group.by = "sample_name")+NoAxes()+ggtitle("tSNE integrated"),
  # DimPlot(DATA_int_log, reduction = "umap", group.by = "sample_name")+NoAxes()+ggtitle("UMAP integrated")
)
```

```{r Paulos_plot, eval=FALSE, include=FALSE}
library(niceRplots)
genes <- c("CD8A", "MYOZ2", "CD3E", "EPCAM", "COL6A1", "CD4")
genes <- c("CDH1")
par(mfrow=c(2,2), mar=c(1,1,1,1))
DATA$cell_id[is.na(DATA$cell_id)] <- ""
#plot_meta(DATA, red = "umap_harmony", feat = "cell_id", cex = 0.5, label = T)
#plot_meta(DATA, red = "umap_harmony", feat = "p", cex = 0.5, label = T)
for(i in genes){
  plot_feat(DATA, red = "umap_harmony", feat = i, cex = 0.5)
}
grep("MYO", rownames(DATA), value = T)
```

```{r Paulos_code, eval=FALSE, include=FALSE}
##################################
# EVALUATE CLUSTERING RESOLUTION #
##################################
DATA <- FindNeighbors(DATA, reduction = "harmony", dims = 1:20, k.param = 20, prune.SNN = 1/15) 

for (res in c(0.1, 0.25, 0.5, 1, 1.5, 2)) {
    DATA <- FindClusters(DATA, graph.name = "RNA_snn", resolution = res, algorithm = 1)
}

library(niceRplots)
par(mfrow = c(1,2))
plot_meta(DATA, red = "umap_harmony", feat = "RNA_snn_res.0.25", cex = 0.5)
plot_meta(DATA, red = "umap_harmony", feat = "RNA_snn_res.1", cex = 0.5, label = T)

# plot_grid(ncol = 3, DimPlot(DATA, reduction = "umap", group.by = "RNA_snn_res.0.5") +
#     ggtitle("leiden_0.5"), DimPlot(DATA, reduction = "umap", group.by = "RNA_snn_res.1") +
#     ggtitle("leiden_1"), DimPlot(DATA, reduction = "umap", group.by = "RNA_snn_res.2") +
#     ggtitle("leiden_2"))

```

## Save seurat object

```{r save_SeuratObj}
##################################
# SAVE INTERMEDIATE SEURAT OJECT #
##################################
#saveRDS(DATA, paste0(result_dir,"SeuratObj_harmony.RDS"))
saveRDS(DATA, paste0(result_dir,"SeuratObj_harmony_filt.RDS"))
#DATA <- readRDS(paste0(result_dir,"SeuratObj_harmony.RDS"))
```

### Session info

```{r}
sessionInfo()
```
