---
title: "Integrate Datasets"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    embed-resources: true
    code-fold: show
params:
  fig.path: "./Figures/02/"
editor_options: 
  chunk_output_type: console
---

```{r background-job, eval=FALSE, include=FALSE}
source("../../bin/render_with_jobs.R")

# quarto
# render_html_with_job(out_dir = lab_dir)
# fs::file_move(path = file, new_path = paste0(lab_dir, file))

# currently using quarto for github and kniter for html due to source code option 
render_git_with_job(fig_path = "./Figures/02/")
# Change the figure path from ./Figures/03/ to ../Figures/03/:
system2(command = "sed", stdout = TRUE,
        args = c("-i", "''","-e", 's/src=\\"\\./src=\\"\\.\\./g',
                 paste0("./md_files/", basename("./02_integrate_ref_data.md"))))

# kniter
knit_html_with_job(out_dir = "../../lab_book/reference_data/02_integrate_reference_data", fig_path = "./Figures/02/")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    fig.width   = 6.6929133858,
    fig.path    = params$fig.path,
    dev         = c("png"),
    dpi         = 300,
    fig.align   = "center",
    message     = FALSE,
    warning     = FALSE,
    fig.process = function(filename){
      new_filename <- stringr::str_remove(string = filename, 
                                        pattern = "-1")
      fs::file_move(path = filename, new_path = new_filename)
      ifelse(fs::file_exists(new_filename), new_filename, filename)}) 
# setwd("/Users/vilkal/work/Brolidens_work/Projects/Spatial_DMPA/src/00_reference_data")
```

### Load data and libraries
```{r Load-Library-and-data}
##################
# LOAD LIBRARIES #
##################
library(tidyverse)
library(Seurat)
library(tidyseurat)
library(cowplot)
library(harmony)

source("../../bin/plotting_functions.R")

#########
# PATHS #
#########
input_dir <- "../../results/01_QC_ref_data/"
result_dir <- "../../results/02_integrate_ref_data/"
if( isFALSE(dir.exists(result_dir)) ) { dir.create(result_dir,recursive = TRUE) }

#############
# LODA DATA #
#############
seuratObj <- readRDS(paste0(input_dir,"seuratObj_filtered.RDS"))

seuratObj <- seuratObj %>% 
  #filter(p == "Li_Y")
  filter(p == "Peng")
```

### Identify Highly Variable Genes (HVG) across samples
```{r Find-HVG}
################################
# SPLIT INTO SEPERATE DATASETS #
################################
seuratObj_nested <- seuratObj %>%
  mutate(batch = sample_name) %>%
  nest(data = -batch) %>%
  #filter(batch == "CX3" | batch == "CX1") %>%
  mutate(data = imap(
    data, ~ .x %>%
      NormalizeData(., normalization.method = "LogNormalize", 
                    verbose = FALSE) %>%
      FindVariableFeatures(selection.method = "vst", 
                           nfeatures = 2000, 
                           verbose = FALSE) )) %>%
  mutate(data = setNames(.[["data"]], .$batch))

#########################################
# FIND HIGLY VARIABLE GENES PER DATASET #
#########################################
hvgs_heat <- seuratObj_nested %>%
  .$data %>%
  map(., ~ .x@assays$RNA@var.features) %>%
  ( function(x){unique(unlist(x)) ->> hvgs_all; return(x)} ) %>%
  # intersect across all samples:
  ( function(x){Reduce(intersect, x) ->> hvgs; return(x)} ) %>% 
  imap_dfc(., ~hvgs_all %in% .x, .id=.y) %>%
  mutate(rownames = hvgs_all) %>%
  column_to_rownames(var = "rownames")

# choose the hvg present in at least two samples:
hig_var <- rownames(hvgs_heat)[rowSums(hvgs_heat)>2]

# remove all VDJ-genes from list of HVG
remove <- str_subset(hig_var, "^IGH|^IGK|^IGL|^TRA|^TRB|^TRD|^TRG")
hig_var <- setdiff(hig_var, remove)
```

### Heatmap of HVG in all samples
```{r 02a_HVG_heatmap, fig.width=10}
pheatmap::pheatmap(t(hvgs_heat * 1), cluster_rows = F, color = c("grey90", "grey20"))
```

### Integration
```{r Integration}
############################
# CCA REDUCTION INTERATION #
############################
# seuratObj_CCA <- seuratObj_split %>%
#   .$data %>%
#   FindIntegrationAnchors(normalization.method = "LogNormalize",
#                          anchor.features = hig_var,
#                          dims = 1:30,
#                          reduction = "cca") %>%
#   IntegrateData(., dims = 1:30, new.assay.name = "CCA")
# 
# saveRDS(seuratObj_CCA, paste0(result_dir,"seuratObj_CCA.RDS"))

############
# HARMONY #
###########
seuratObj <- seuratObj %>%
  #filter(sample_name == "CX3" | sample_name == "CX1") %>%
  NormalizeData(verbose = FALSE) %>%
  FindVariableFeatures(selection.method = "vst",
                      nfeatures = 4000,
                      verbose = FALSE) %>%
  ScaleData(verbose = FALSE, features = hig_var ) %>%
  RunPCA(verbose = FALSE, npcs = 50) %>%
  RunUMAP(dims = 1:50, n.components = 2L) 

seuratObj <- seuratObj %>%
  RunHarmony(group.by.vars = "sample_name", 
             reduction = "pca", 
             dims.use = 1:50, 
             assay.use = "RNA") %>%
  RunUMAP(dims = 1:30, 
          reduction = "harmony",
          reduction.name = "umap_harmony")

######################
# SCT NORMALIZATION #
#####################
# seuratObj_sct <- seuratObj_nested %>%
#   mutate(data = map(data, ~ SCTransform(.x, verbose = FALSE))) %>%
#   .$data %>%
#   ( function(x){SelectIntegrationFeatures(x) ->> af; return(x)} ) %>%
#   PrepSCTIntegration(anchor.features = af) %>%
#   FindIntegrationAnchors(normalization.method = "SCT",
#                          anchor.features = af) %>%
#   IntegrateData(normalization.method = "SCT") 
# 
# seuratObj_sct <- readRDS(paste0(result_dir,"seuratObj_sct.RDS"))

```

### Plot before and after integration
```{r 02b_Plot_dim_reduction, fig.width=10, fig.height=10}
res <- c("PC", "harmony", "UMAP", "umap_harmony")
title <- c("PCA raw data", "PCA Harmony integrated", "UMAP raw data", "UMAP Harmony integrated")
p <- map2(res, title, ~plot_clusters.fun(seuratObj, cluster="sample_name", red=.x, lable=FALSE, title=.y))
plot_grid(ncol = 2, 
         plotlist = p)
```

### Plot marker genes
```{r 02c_plot_marker_genes, fig.width=10}
################################
# VISUALIZE EXPR. OF KEY GENES #
################################
library(viridis)
col=c("grey90","grey80","grey60","navy","black")
genes <- c("CD8A", "SFRP2", "CD3E")
# genes <- c("CD8A", "MYOZ2", "CD3E", "EPCAM", "COL6A1", "CD4")

# get approximate max value for among all features (genes)
red <- seuratObj@reductions[["umap_harmony"]]@cell.embeddings
max <- quantile(red,0.99,na.rm = T)

#p <- map(genes, ~plot_genes.fun(seuratObj, .x, maxs = max))
p <- map(genes, ~plot_genes.fun(seuratObj, .x, red = "umap_harmony"))
plot_grid(ncol = 3, 
          plotlist = p)

```

### Save seurat object
```{r save-SeuratObject}
##################################
# SAVE INTERMEDIATE SEURAT OJECT #
##################################
saveRDS(seuratObj, paste0(result_dir,"seuratObj_harmony.RDS"))
#seuratObj <- readRDS(paste0(result_dir,"seuratObj_harmony.RDS"))
```

## Session info
```{r}
sessionInfo()
```

## Paulos base R code
```{r Paulos_HVG, eval=FALSE, include=FALSE}
seuratObj.list <- SplitObject(seuratObj, split.by = "sample_name")

for (i in 1:length(seuratObj.list)) {
    seuratObj.list[[i]] <- NormalizeData(seuratObj.list[[i]], verbose = FALSE)
    seuratObj.list[[i]] <- FindVariableFeatures(seuratObj.list[[i]], selection.method = "vst",
        nfeatures = 2000, verbose = FALSE)
}

hvgs_per_dataset <- lapply(seuratObj.list, function(x) {
    x@assays$RNA@var.features
})
# venn::venn(hvgs_per_dataset,opacity = .4,zcolor = scales::hue_pal()(3),cexsn
# = 1,cexil = 1,lwd=1,col='white',frame=F,borders = NA)

temp <- unique(unlist(hvgs_per_dataset))
overlap <- sapply(hvgs_per_dataset, function(x) {
    temp %in% x
})
rownames(overlap) <- temp
pheatmap::pheatmap(t(overlap * 1), cluster_rows = F, color = c("grey90", "grey20"))
```

```{r Paulos_harmony, eval=FALSE, include=FALSE}
hig_var <- rownames(overlap)[rowSums(overlap)>2]
seuratObj <- seuratObj %>%
  NormalizeData(verbose = FALSE) %>%
  FindVariableFeatures(selection.method = "vst",
                      nfeatures = 4000,
                      verbose = FALSE) %>%
  ScaleData(verbose = FALSE, features = hig_var ) %>%
  RunPCA(verbose = FALSE, npcs = 50) %>%
  RunUMAP(dims = 1:50, n.components = 2L) 

seuratObj <- RunHarmony(seuratObj, group.by.vars = "sample_name", reduction = "pca",
    dims.use = 1:50, assay.use = "RNA")

seuratObj <- RunUMAP(seuratObj, dims = 1:30, reduction = "harmony", reduction.name = "umap_harmony")
```

```{r Plot_dimreduction, eval=FALSE, fig.width=10, include=FALSE}
plot_grid(ncol = 2,
  DimPlot(seuratObj, reduction = "pca", group.by = "sample_name")+NoAxes()+ggtitle("PCA raw_data"),
  DimPlot(seuratObj, reduction = "umap", group.by = "sample_name")+NoAxes()+ggtitle("UMAP raw_data"),
  
  DimPlot(seuratObj, reduction = "harmony", group.by = "sample_name")+NoAxes()+ggtitle("harmony integrated"),
  DimPlot(seuratObj, reduction = "umap_harmony", group.by = "sample_name")+NoAxes()+ggtitle("UMAP harmony integrated")
  
  # DimPlot(seuratObj_int_log, reduction = "pca", group.by = "sample_name")+NoAxes()+ggtitle("PCA integrated"),
  # DimPlot(seuratObj_int_log, reduction = "tsne", group.by = "sample_name")+NoAxes()+ggtitle("tSNE integrated"),
  # DimPlot(seuratObj_int_log, reduction = "umap", group.by = "sample_name")+NoAxes()+ggtitle("UMAP integrated")
)
```

```{r Paulos_plot, eval=FALSE, include=FALSE}
library(niceRplots)
genes <- c("CD8A", "MYOZ2", "CD3E", "EPCAM", "COL6A1", "CD4")
par(mfrow=c(2,2), mar=c(1,1,1,1))
seuratObj$cell_id[is.na(seuratObj$cell_id)] <- ""
#plot_meta(seuratObj, red = "umap_harmony", feat = "cell_id", cex = 0.5, label = T)
#plot_meta(seuratObj, red = "umap_harmony", feat = "p", cex = 0.5, label = T)
for(i in genes){
  plot_feat(seuratObj, red = "umap_harmony", feat = i, cex = 0.5)
}
grep("MYO", rownames(seuratObj), value = T)
```

```{r Paulos_code, eval=FALSE, include=FALSE}
##################################
# EVALUATE CLUSTERING RESOLUTION #
##################################
seuratObj <- FindNeighbors(seuratObj, reduction = "harmony", dims = 1:20, k.param = 20, prune.SNN = 1/15) 

for (res in c(0.1, 0.25, 0.5, 1, 1.5, 2)) {
    seuratObj <- FindClusters(seuratObj, graph.name = "RNA_snn", resolution = res, algorithm = 1)
}

library(niceRplots)
par(mfrow = c(1,2))
plot_meta(seuratObj, red = "umap_harmony", feat = "RNA_snn_res.0.25", cex = 0.5)
plot_meta(seuratObj, red = "umap_harmony", feat = "RNA_snn_res.1", cex = 0.5, label = T)

# plot_grid(ncol = 3, DimPlot(seuratObj, reduction = "umap", group.by = "RNA_snn_res.0.5") +
#     ggtitle("leiden_0.5"), DimPlot(seuratObj, reduction = "umap", group.by = "RNA_snn_res.1") +
#     ggtitle("leiden_1"), DimPlot(seuratObj, reduction = "umap", group.by = "RNA_snn_res.2") +
#     ggtitle("leiden_2"))

```